export const types = {
    // auth
    SET_USER_TOKEN: 'SET_USER_TOKEN',
    SET_USER: 'SET_USER',

    // login
    USER_LOGIN_REQUEST: 'USER_LOGIN_REQUEST',
    USER_LOGIN_SUCCESS: 'USER_LOGIN_SUCCESS',
    USER_LOGIN_FAIL: 'USER_LOGIN_FAIL',

     // logout
     USER_LOGOUT_REQUEST: 'USER_LOGOUT_REQUEST',
     USER_LOGOUT_SUCCESS: 'USER_LOGOUT_SUCCESS',
     USER_LOGOUT_FAIL: 'USER_LOGOUT_FAIL',

    // register
    SET_REGISTER_STEP: 'SET_REGISTER_STEP',
    USER_REGISTER_REQUEST: 'USER_REGISTER_REQUEST',
    USER_REGISTER_SUCCESS: 'USER_REGISTER_SUCCESS',
    USER_REGISTER_FAIL: 'USER_REGISTER_FAIL',

    // profile
    USER_CREATE_PROFILE_REQUEST: 'USER_CREATE_PROFILE_REQUEST',
    USER_CREATE_PROFILE_SUCCESS: 'USER_CREATE_PROFILE_SUCCESS',
    USER_CREATE_PROFILE_FAIL: 'USER_CREATE_PROFILE_FAIL',

    // password
    USER_SET_PASSWORD: 'USER_SET_PASSWORD',
    USER_FORGOT_PASSWORD: 'USER_FORGOT_PASSWORD',
    USER_RESET_PASSWORD: 'USER_RESET_PASSWORD',

    // UI
    INITIALIZE: 'INITIALIZE',
    USER_LOGOUT: 'USER_LOGOUT',
    SET_AUTH_TAB: 'SET_AUTH_TAB'
};
