export const types = {
    // tokens
    SET_USER_TOKEN: 'SET_USER_TOKEN',
    SET_RESET_TOKEN: 'SET_RESET_TOKEN',
    SET_RESET_TEMPORARY_TOKEN: 'SET_RESET_TEMPORARY_TOKEN',

    // user
    SET_USER: 'SET_USER',
    GET_USER_INFO_REQUEST: 'GET_USER_INFO_REQUEST',
    GET_USER_INFO_SUCCESS: 'GET_USER_INFO_SUCCESS',
    GET_USER_INFO_FAIL: 'GET_USER_INFO_FAIL',

    // login
    USER_LOGIN_REQUEST: 'USER_LOGIN_REQUEST',
    USER_LOGIN_SUCCESS: 'USER_LOGIN_SUCCESS',
    USER_LOGIN_FAIL: 'USER_LOGIN_FAIL',

    // logout
    USER_LOGOUT_REQUEST: 'USER_LOGOUT_REQUEST',
    USER_LOGOUT_SUCCESS: 'USER_LOGOUT_SUCCESS',
    USER_LOGOUT_FAIL: 'USER_LOGOUT_FAIL',

    // register
    SET_REGISTER_STEP: 'SET_REGISTER_STEP',
    USER_REGISTER_REQUEST: 'USER_REGISTER_REQUEST',
    USER_REGISTER_SUCCESS: 'USER_REGISTER_SUCCESS',
    USER_REGISTER_FAIL: 'USER_REGISTER_FAIL',

    // profile
    USER_CREATE_PROFILE_REQUEST: 'USER_CREATE_PROFILE_REQUEST',
    USER_CREATE_PROFILE_SUCCESS: 'USER_CREATE_PROFILE_SUCCESS',
    USER_CREATE_PROFILE_FAIL: 'USER_CREATE_PROFILE_FAIL',
    USER_UPDATE_PROFILE_REQUEST: 'USER_UPDATE_PROFILE_REQUEST',
    USER_UPDATE_PROFILE_SUCCESS: 'USER_UPDATE_PROFILE_SUCCESS',
    USER_UPDATE_PROFILE_FAIL: 'USER_UPDATE_PROFILE_FAIL',

    // email confirm
    USER_CONFIRM_EMAIL_REQUEST: 'USER_CONFIRM_EMAIL_REQUEST',
    USER_CONFIRM_EMAIL_SUCCESS: 'USER_CONFIRM_EMAIL_SUCCESS',
    USER_CONFIRM_EMAIL_FAIL: 'USER_CONFIRM_EMAIL_FAIL',

    // phone confirm
    USER_CONFIRM_SEND_SMS_REQUEST: 'USER_CONFIRM_SEND_SMS_REQUEST',
    USER_CONFIRM_SEND_SMS_SUCCESS: 'USER_CONFIRM_SEND_SMS_SUCCESS',
    USER_CONFIRM_SEND_SMS_FAIL: 'USER_CONFIRM_SEND_SMS_FAIL',
    USER_CONFIRM_PHONE_REQUEST: 'USER_CONFIRM_PHONE_REQUEST',
    USER_CONFIRM_PHONE_SUCCESS: 'USER_CONFIRM_PHONE_SUCCESS',
    USER_CONFIRM_PHONE_FAIL: 'USER_CONFIRM_PHONE_FAIL',

    // password
    USER_FORGOT_PASSWORD_REQUEST: 'USER_FORGOT_PASSWORD_REQUEST',
    USER_FORGOT_PASSWORD_SUCCESS: 'USER_FORGOT_PASSWORD_SUCCESS',
    USER_FORGOT_PASSWORD_FAIL: 'USER_FORGOT_PASSWORD_FAIL',
    USER_RESET_PASSWORD_REQUEST: 'USER_RESET_PASSWORD_REQUEST',
    USER_RESET_PASSWORD_SUCCESS: 'USER_RESET_PASSWORD_SUCCESS',
    USER_RESET_PASSWORD_FAIL: 'USER_RESET_PASSWORD_FAIL',
    USER_RESET_PASSWORD_CONFIRM_PHONE_REQUEST: 'USER_RESET_PASSWORD_CONFIRM_PHONE_REQUEST',
    USER_RESET_PASSWORD_CONFIRM_PHONE_SUCCESS: 'USER_RESET_PASSWORD_CONFIRM_PHONE_SUCCESS',
    USER_RESET_PASSWORD_CONFIRM_PHONE_FAIL: 'USER_RESET_PASSWORD_CONFIRM_PHONE_FAIL',

    // UI
    INITIALIZE: 'INITIALIZE',
    SET_AUTH_TAB: 'SET_AUTH_TAB'
};
